name: CI

on:
  push:
    branches: master

jobs:

  sync:
    name: Sync repositories
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Sync terraform providers
        run: |
          cd schemas-extractor
          export GOPATH=/tmp/
          make
          mv schemas/* ../terraform/model/providers/
          mv providers.list ../terraform/model

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: latest-sync
          path: terraform

  commit-results:
    name: Commit results
    runs-on: ubuntu-latest
    needs: [sync]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Fetch artifacts
        uses: actions/download-artifact@v1
        with:
          name: latest-sync

      - name: Move around
        run: |
          sudo apt update
          sudo apt install tree
          git status
          tree
          mv latest-sync/* terraform/
          git status

      - name: Set commit message
        id: commit
        run: |
          echo "::set-output name=desc::Update metadata as of  $(date)"

      - uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: ${{ steps.commit.outputs.desc }}
          branch: sync
          commit_user_name: Alexander Chernov
          commit_user_email: alekcander@gmail.com

#      - name: Git Status
#        id: debug
#        run: |
#          git status
